FROM mysql:latest

# Set environment variables for MySQL
ENV MYSQL_DATABASE=recipe_database
ENV MYSQL_ROOT_PASSWORD=Terra3927
ENV MYSQL_USER=spring
ENV MYSQL_PASSWORD=spring

# Expose the MySQL port
EXPOSE 3306